#!/bin/bash

FOLDER_PATH="$(pwd)"

for file in "$FOLDER_PATH"/{*,.*}; do
  if [[ "$file" == "$FOLDER_PATH/." || "$file" == "$FOLDER_PATH/.." ]]; then
    continue
  fi

  if [[ -f "$file" && $(file --mime-type -b "$file") == text/* ]]; then
    cat "$file" | pbcopy
    echo "Copied contents of: $file"
    read -p "Press Enter for the next file..."
  else
    echo "Skipped non-text file: $file"
  fi
done

