#!/bin/bash

# Extract the base name without the .c extension
output_file=$(basename "$1" .c)

# Compile the C program with necessary architecture flags
gcc -arch arm64 "$1" -o "$output_file"

if [ $? -eq 0 ]; then
  shift
  ./"$output_file" "$@"
else
  echo "Compilation failed"
fi

# Delete the file to avoid clutter and allow rapid prototyping/testing
rm -rf "$output_file"
