#!/bin/bash
set -e

if [ "$#" -ne 2 ]; then
    echo "Usage: yt <url> <output_name>"
    exit 1
fi

url="$1"
output_name="$2"

yt-dlp \
  -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]" \
  --merge-output-format mp4 \
  --add-header "User-Agent: Mozilla/5.0" \
  --add-header "Referer: $url" \
  -o "${output_name}.mp4" \
  "$url"
